platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

target 'XTInputKitDemo' do
  pod 'XTInputKit', :path => '../'
#  pod 'XTILogerManager', :git => 'https://github.com/xt-input/XTILogerManager.git', :tag => '0.0.5'
end
