project './XTInputKit/XTInputKitDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'XTInputKitDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XTInputKit
  pod 'XTInputKit', :path => '../'
end
