install! 'cocoapods',
  :generate_multiple_pod_projects => true,
  :incremental_installation => true

# Uncomment the next line to define a global platform for your project
platform :ios, 10.0
inhibit_all_warnings!

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XTInputKitDemo
  pod 'LookinServer', :configurations => ['Debug']
  
  pod 'XTInputKit', :path => '../'
  pod 'Kingfisher'
end
